<?php
/*
 * author s.haendler@covi.de
 * version 1.0
 * lastchange 2017-06-29
*/

include(__DIR__."/config.php");$mtime=0;$ctime=0;$msum=array();$filelist=file(str_replace(LOCALHUB,'',__DIR__).'/.localhub');foreach($filelist AS $fk=>$fv):$fdata=''; $fv=trim($fv); if (count(explode('=>',$fv))>1): $fdtmp = explode('=>',trim($fv)); $fv = $fdtmp[0]; if (is_file(str_replace(LOCALHUB, '', __DIR__).'/'.trim($fv))): $fdata = stat(str_replace(LOCALHUB, '', __DIR__).'/'.trim($fv)); endif; else: if (is_file(str_replace(LOCALHUB, '', __DIR__).'/'.trim($fv))): $fdata = stat(str_replace(LOCALHUB, '', __DIR__).'/'.trim($fv)); endif; endif; if (is_array($fdata)): $csum = md5(trim($fv).$fdata['size'].$fdata['mtime'].$fdata['ctime']); if ($mtime<$fdata['mtime']): $mtime = $fdata['mtime']; endif; if ($ctime<$fdata['ctime']): $ctime = $fdata['ctime']; endif; $msum[] = $csum; endif; endforeach; if (count($msum)!=count($filelist)): exit("<p style='color: rgb(164,0,0);'>number of local files (".count($msum).") differs from number of files in list (".count($filelist)."). aborting creation of nightly build</p>"); else: $buffer = array(0 => array('version' => BASEVERSION.".0", 'num' => count($msum))); $versions = false; $newversion = false; if (is_file(__DIR__.'/'.VERSIONS)): $versions = file(__DIR__.'/'.VERSIONS); endif; if ($versions): foreach ($versions AS $vk => $vv): if (trim($vv)!=''): $vdata = explode(":", $vv); if (count($vdata)>1): $buffer[$vdata[0]] = array('version' => $vdata[1], 'num' => $vdata[2], 'timestamp' => $vdata[0]); endif; endif; endforeach; krsort($buffer); endif; $value = reset($buffer); $getversion = explode(".", $value['version']); $lstversion = intval($getversion[(count($getversion)-1)]); $lstdate = intval($value['timestamp']); $nxtversion = $lstversion+1; if (!(array_key_exists($ctime, $buffer))): $versions = fopen(__DIR__.'/'.VERSIONS, 'a'); $newversion = BASEVERSION.".".$nxtversion; fwrite($versions, $ctime.":".$newversion.":".count($msum).":".md5(implode('',$msum)).PHP_EOL); $newversion = BASEVERSION.".".(count($buffer)+1); fclose($versions); endif; if ($newversion!==false): $zip = new ZipArchive(); $filename = SLUG."-".$newversion.".zip"; if ($zip->open(__DIR__.'/'.$filename, ZipArchive::CREATE)!==TRUE): exit("<p style='color: rgb(164,0,0);'>could not create zip file of nightly build</p>"); endif; foreach ($filelist AS $fk => $fv): $fdata = ''; $fv=trim($fv); if (count(explode('=>',$fv))>1): $fdtmp = explode('=>',trim($fv)); $fv = trim($fdtmp[0]); if (is_file(str_replace(LOCALHUB, '', __DIR__).'/'.trim($fv))): $zip->addFile(trim($fdtmp[0]),trim($fdtmp[1])); endif; else: if (is_file(str_replace(LOCALHUB, '', __DIR__).'/'.trim($fv))): $zip->addFile($fv); endif; endif; endforeach; $zip->close(); elseif (is_file(__DIR__.'/'.SLUG."-".BASEVERSION.'.'.$lstversion.'.zip')): echo "<p>Nightly Build: <a href='/".LOCALHUB."/".SLUG."-".BASEVERSION.'.'.$lstversion.".zip'>".SLUG."-".BASEVERSION.'.'.$lstversion.".zip</a> (".date(LOCALDATE, $lstdate).")</p>"; endif; endif;

?>
